name: "Mdp-9x9_Image"
framework: "mdp"
n_total_timesteps: 1000000
kwargs:
  seed: 1
  grid_shape: [9, 9]
  reward_function: move_to_a_point
  dense_reward: True
  state_representation: image
eval_kwargs:
  seed: 1
  grid_shape: [9, 9]
  reward_function: move_to_a_point
  dense_reward: False
  state_representation: image
cnn_policy: True
deterministic_eval: False
jax_enable_x64: True
n_envs: 4