name: "Mdp-2x2_Seeds"
framework: "mdp"
n_total_timesteps: 1000
kwargs:
  grid_shape: [6, 6]
  reward_function: move_to_a_point
  state_representation: vector
  number_terminal_states: 2
  max_steps_in_episode: 15
  reward_delay_prob: 0.5
eval_kwargs:
  grid_shape: [6, 6]
  reward_function: move_to_a_point
  state_representation: vector
  number_terminal_states: 2
  max_steps_in_episode: 15
  reward_delay_prob: 0.5
cnn_policy: False
deterministic_eval: True
jax_enable_x64: True
n_envs: 1