name: "Mdp-2x2_Terminal"
framework: "mdp"
n_total_timesteps: 100
kwargs:
  seed: 1
  grid_shape: [4, 4]
  reward_function: move_to_a_point
  state_representation: vector
  irrelevant_features: False
  number_terminal_states: 4
eval_kwargs:
  seed: 1
  grid_shape: [4, 4]
  reward_function: move_to_a_point
  state_representation: vector
  irrelevant_features: False
  number_terminal_states: 4
cnn_policy: False
deterministic_eval: True
jax_enable_x64: True
n_envs: 1