hp_defaults:
  buffer_prio_sampling: true
  buffer_alpha: 0.9
  buffer_beta: 0.74
  buffer_epsilon: 1.432642e-06
  buffer_batch_size: 16
  buffer_size: 12312
  initial_epsilon: 0.6
  target_epsilon: 0.03
  exploration_fraction: 0.3
  gamma: 0.9
  gradient_steps: 8
  learning_rate: 0.00066
  learning_starts: 1050
  normalize_observations: false
  train_freq: 10
  use_target_network: true
  target_update_interval: 1039
  tau: 0.92
hp_values:
  buffer_size:
  - 1000
  - 5000
  - 10000
  - 25000
  - 50000
  gamma:
  - 0.75
  - 0.85
  - 0.9
  - 0.95
  - 0.999
  gradient_steps:
  - 1
  - 2
  - 4
  - 8
  - 16
  learning_rate:
  - 1.0e-05
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  learning_starts:
  - 100
  - 500
  - 1000
  - 2000
  - 5000
  train_freq:
  - 1
  - 2
  - 4
  - 8
  - 16
  target_update_interval:
  - 10
  - 25
  - 50
  - 100
  - 200
  - 400
  - 800
  - 1600
env:
  grid_shape:
  - - 5
    - 5
  - - 10
    - 10
  - - 15
    - 15
  max_steps_in_episode:
  - 100
  transition_noise:
  - 0.0
  frac_term_states:
  - 0.0
  - 0.01
  - 0.05
  success_reward:
  - 10.0
  - 1.0
  - 0.0
  terminal_state_penalty:
  - -10.0
  - -1.0
  - 0.0
  reward_shift:
  - 0.0
  manhattan_dist_scaling:
  - 0.0
  - 0.1
  - 1.0
  reward_noise:
  - 0.0
  reward_scaling_factor:
  - 1.0
  reward_probability:
  - 1.0
  reward_delay_prob:
  - 0.0
seeds:
- 1
- 10
- 20
- 25
- 42
