# @package _global_
algorithm: dqn
hp_config:
  buffer_prio_sampling: true
  buffer_alpha: 0.9
  buffer_beta: 0.74
  buffer_epsilon: 1.432643e-06
  buffer_batch_size: 16
  buffer_size: 10000
  initial_epsilon: 1.0
  target_epsilon: 0.1
  exploration_fraction: 0.1
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 0.0001
  learning_starts: 500
  normalize_observations: false
  train_freq: 4
  use_target_network: true
  target_update_interval: 500
  tau: 0.1
nas_config:
  activation: relu
  hidden_size: 64
