seed: 0
hyperparameters:
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.7
    default: 0.9
    log: false
  hp_config.buffer_batch_size:
    type: categorical
    choices:
      - 8
      - 16
      - 32
    default: 16
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.7
    default: 0.9
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1e-1
    lower: 1e-7
    default: 1e-6
    log: true
  hp_config.buffer_prio_sampling:
    type: categorical
    choices:
      - true
      - false
    default: false
  hp_config.buffer_size:
    type: categorical
    choices:
      - 20000
      - 15000
      - 10000
      - 5000
    default: 10000
  hp_config.initial_epsilon:
    type: uniform_float
    upper: 1.0
    lower: 0.5
    default: 1.0
    log: false
  hp_config.exploration_fraction:
    type: uniform_float
    upper: 0.3
    lower: 0.001
    default: 0.1
    log: false
  hp_config.target_epsilon:
    type: uniform_float
    upper: 0.4
    lower: 0.0
    default: 0.05
    log: false
  hp_config.gamma:
    type: uniform_float
    upper: 1.0
    lower: 0.95
    default: 0.99
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.01
    lower: 0.00001
    default: 0.001
    log: true
  hp_config.learning_starts:
    type: categorical
    choices:
      - 600
      - 800
      - 1000
      - 1200
      - 1400
    default: 1000
  hp_config.use_target_network:
    type: categorical
    choices:
      - true
      - false
    default: true
  hp_config.target_update_interval:
    type: uniform_int
    upper: 2000
    lower: 800
    default: 1000
    log: false
  hp_config.tau:
    type: uniform_float
    upper: 1.0
    lower: 0.9
    default: 1.0
    log: false
  hp_config.gradient_steps:
    type: uniform_int
    upper: 10
    lower: 1
    default: 1
    log: false
  hp_config.train_freq:
    type: uniform_int
    upper: 10
    lower: 1
    default: 1
    log: false
  nas_config.activation:
    type: categorical
    choices:
      - 'tanh'
      - 'relu'
    default: 'relu'
  nas_config.hidden_size:
    type: categorical
    choices:
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
    default: 64
conditions:
  - child: hp_config.target_update_interval
    parent: hp_config.use_target_network
    value: true
    type: EQ
  - child: hp_config.tau
    parent: hp_config.use_target_network
    value: true
    type: EQ
  - child: hp_config.buffer_epsilon
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_alpha
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_beta
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
