# Parameters for Grid Search Experiment
experiment_name: 'Grid_Search_Experiment'
state_representation: vector
cnn_policy: False
n_total_timesteps: 1000
grid_shape: [10, 10]
n_envs: 1
seed: 42 
n_eval_steps: 50
n_eval_episodes: 2
different_seeds: [1,10]
device: 'cpu'

# Environment Properties for Grid Search
# 5 Values pro Property
env_config:
  grid_shape:
    values: [[5,5], [6,6]]
  max_steps_in_episode:
    values: [50]
  transition_noise:
    values: [0.0]
  frac_term_states:
    values: [0.0]
  success_reward:
    values: [10.0, 1.0, 0.0]
  terminal_state_penalty:
    values: [-1.0]
  reward_shift:
    values: [0.0]
  manhattan_dist_scaling:
    values: [1.0]
  reward_noise:
    values: [0.0]
  reward_scaling_factor:
    values: [1.0]
  reward_probability:
    values: [1.0]
  reward_delay_prob:
    values: [0.0]
### N_envs tunen (rel. to train_freq)
# Minigrid anschauen

# Hyperparameters for Grid Search
hp_config:
  buffer_prio_sampling: 
    value_range: []
    default: false
  buffer_alpha: 
    value_range: []
    default: 0.9
  buffer_beta:
    value_range: []
    default: 0.9
  buffer_epsilon: 
    value_range: []
    default: 0.001
  buffer_batch_size: 
    value_range: []
    default: 16
  buffer_size:
    value_range: []
    default: 100000
  initial_epsilon: 
    value_range: []
    default: 1.0
  target_epsilon: 
    value_range: []
    default: 0.05
  exploration_fraction: 
    value_range: []
    default: 0.1
  gamma:
    value_range: [0.95, 0.99, 0.999]
    default: 0.99
  gradient_steps: 
    value_range: []
    default: 1
  learning_rate:
    value_range: [0.01, 0.001]
    default: 0.0003
  learning_starts:
    value_range: []
    default: 128
  normalize_observations:
    value_range: []
    default: false
  train_freq:
    value_range: []
    default: 4
  use_target_network:
    value_range: []
    default: true
  target_update_interval:
    value_range: []
    default: 1000
  tau: 
    value_range: []
    default: 1.0

# Neural Archticecture Search Configurations
nas_config:
  activation:
    value_range: []
    default: relu
  hidden_size:
    value_range: []
    default: 64

hydra:
  run:
    dir: results/${experiment_name}
  sweep:
    dir: results/${experiment_name}
  job:
    chdir: true